name: Import from Notion

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      pageId:
        description: 'Notion page ID'     
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout src branch
        uses: actions/checkout@v3
        with:
          ref: src

      - name: Run script
        id: checker
        run: ./ImportFromNotion.ps1 $env:NOTION_PAGE_ID
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_PAGE_ID: ${{ inputs.pageId }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ inputs.pageId }}
          base: src